hotlink: false
origin: 'http://camp2019.drupalpune.com'
origin_dir: sites/camp2019/files
use_imagecache_root: true
verify: true
_core:
  default_config_hash: CQLKbL2AgHGqE2ilC8yF4Mhg142d5_lgO6nJF7Ws66w
